sudo: required

services:
  - docker

script:
  - chmod +x dckr

  - docker pull postgres

  - docker run -d --name data tianon/true
  - docker run -d --name base --volumes-from=data beevelop/base
  - docker run -d --name linky --volumes-from=base --link base busybox

  - ./dckr id linky
  - ./dckr ip linky
  - ./dckr links linky
  - ./dckr env linky
  - ./dckr cmd linky
  - ./dckr volf linky
  - ./dckr vols linky

  - ./dckr clean
  - ./dckr kill

  - docker run -d --name data tianon/true
  - docker run -d --name base --volumes-from=data beevelop/base
  - docker run -d --name linky --volumes-from=base --link base busybox

  - ./dckr nuke